# Generated by Django 3.1.2 on 2021-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('amout', models.IntegerField(default=0)),
                ('charityusername', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='charityuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
