# Generated by Django 3.1.2 on 2021-04-13 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210412_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='amout',
            new_name='amount',
        ),
    ]
