# Generated by Django 3.1.2 on 2021-04-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charityuser',
            old_name='amout',
            new_name='amount',
        ),
    ]
